// Terminal Commands
export const AVAILABLE_COMMANDS = [
  "help",
  "ls",
  "ls -a",
  "about",
  "skills",
  "projects",
  "contact",
  "experience",
  "education",
  "packages",
  "recommend",
  "clear",
  "clear-data",
  "export-data",
  "settings",
];

export type CommandName = typeof AVAILABLE_COMMANDS[number];

// Command Data
export const COMMAND_DATA: Record<string, string[]> = {
  help: [
    "📋 Available Commands:",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "Professional Info:",
    "  about       - Who I am and my technical approach",
    "  experience  - Work history and achievements",
    "  skills      - Technical skills and expertise",
    "  projects    - Technical challenges I solve",
    "  packages    - NPM packages (if available)",
    "",
    "Get in Touch:",
    "  contact     - How to reach me",
    "  recommend   - Write a LinkedIn recommendation",
    "",
    "Terminal Commands:",
    "  help        - Show this help message",
    "  ls          - List available commands",
    "  ls -a       - List all commands (same as help)",
    "  clear       - Clear terminal screen",
    "  settings    - Open settings panel (or right-click)",
    "  clear-data  - Clear all stored data (⚠️  Warning!)",
    "  export-data - Export all data to JSON file",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "⌨️  Keyboard Shortcuts:",
    "════════════════════════════════════════════════════════════════",
    "  Ctrl+L           - Clear screen",
    "  Ctrl+,           - Open settings",
    "  Ctrl+T           - New tab",
    "  Ctrl+W           - Close tab",
    "  Ctrl+Tab         - Next tab",
    "  Ctrl+Shift+Tab   - Previous tab",
    "  Up/Down          - Navigate command history",
    "  Tab              - Auto-complete commands",
  ],
  ls: [
    "📋 Available Commands:",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "Professional Info:",
    "  about       - Who I am and my technical approach",
    "  experience  - Work history and achievements",
    "  skills      - Technical skills and expertise",
    "  projects    - Technical challenges I solve",
    "  packages    - NPM packages (if available)",
    "",
    "Get in Touch:",
    "  contact     - How to reach me",
    "  recommend   - Write a LinkedIn recommendation",
    "",
    "Terminal Commands:",
    "  help        - Show this help message",
    "  ls          - List available commands",
    "  ls -a       - List all commands (same as help)",
    "  clear       - Clear terminal screen",
    "  settings    - Open settings panel (or right-click)",
    "  clear-data  - Clear all stored data (⚠️  Warning!)",
    "  export-data - Export all data to JSON file",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "⌨️  Keyboard Shortcuts:",
    "════════════════════════════════════════════════════════════════",
    "  Ctrl+L           - Clear screen",
    "  Ctrl+,           - Open settings",
    "  Ctrl+T           - New tab",
    "  Ctrl+W           - Close tab",
    "  Ctrl+Tab         - Next tab",
    "  Ctrl+Shift+Tab   - Previous tab",
    "  Up/Down          - Navigate command history",
    "  Tab              - Auto-complete commands",
  ],
  "ls -a": [
    "📋 Available Commands:",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "Professional Info:",
    "  about       - Who I am and my technical approach",
    "  experience  - Work history and achievements",
    "  skills      - Technical skills and expertise",
    "  projects    - Technical challenges I solve",
    "  packages    - NPM packages (if available)",
    "",
    "Get in Touch:",
    "  contact     - How to reach me",
    "  recommend   - Write a LinkedIn recommendation",
    "",
    "Terminal Commands:",
    "  help        - Show this help message",
    "  ls          - List available commands",
    "  ls -a       - List all commands (same as help)",
    "  clear       - Clear terminal screen",
    "  settings    - Open settings panel (or right-click)",
    "  clear-data  - Clear all stored data (⚠️  Warning!)",
    "  export-data - Export all data to JSON file",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "⌨️  Keyboard Shortcuts:",
    "════════════════════════════════════════════════════════════════",
    "  Ctrl+L           - Clear screen",
    "  Ctrl+,           - Open settings",
    "  Ctrl+T           - New tab",
    "  Ctrl+W           - Close tab",
    "  Ctrl+Tab         - Next tab",
    "  Ctrl+Shift+Tab   - Previous tab",
    "  Up/Down          - Navigate command history",
    "  Tab              - Auto-complete commands",
  ],
  about: [
    "🧑‍💻 About Me",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "I'm a Software Engineer with over 5 years of",
    "experience designing, developing, and scaling real-world web applications.",
    "",
    "My focus isn't just on 'writing code' — I work on architectural",
    "decisions, long-term quality, and building systems that future teams",
    "can develop without friction.",
    "",
    "In projects I've been involved in:",
    "",
    "  ✓ Migrated legacy code to maintainable architectures",
    "  ✓ Designed and implemented Design Systems from scratch",
    "  ✓ Defined standards that enforce quality, not recommend it",
    "",
    "I'm not satisfied with code that just 'works';",
    "Code must be readable, testable, scalable, and bulletproof.",
    "",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "💡 My Technical Approach:",
    "",
    "I don't have bias towards tools. Every decision must answer:",
    "",
    "  • Why this approach?",
    "  • What are the trade-offs?",
    "  • What happens to the team in 6 months?",
    "",
    "My core principles:",
    "",
    "  → Domain vs Shared separation",
    "  → Server State ≠ Client State",
    "  → Performance before fancy animations",
    "  → Readability before clever code",
  ],
  skills: [
    "🛠️ Technical Skills",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "Frontend:",
    "  • React, Next.js, TypeScript, Remix, Solid.js",
    "  • Modern CSS: Tailwind, CSS-in-JS, CSS Modules",
    "  • SSR, SSG, ISR strategies",
    "  • Web Vitals optimization (LCP, CLS, INP)",
    "",
    "Backend:",
    "  • Python, Django",
    "  • NestJS, Node.js",
    "  • RESTful API design",
    "  • Database design & optimization",
    "",
    "State & Data Management:",
    "  • Redux, React Query, Zustand",
    "  • Server State vs Client State separation",
    "  • Advanced caching strategies",
    "",
    "Architecture & Patterns:",
    "  • Monorepo (Nx, Turborepo)",
    "  • Micro-Frontend Architecture",
    "  • Design Systems",
    "  • Domain-Driven Design (Frontend)",
    "  • Clean Architecture principles",
    "",
    "Quality & Performance:",
    "  • Lighthouse optimization (100 scores achieved)",
    "  • Core Web Vitals",
    "  • Testing: Playwright, Jest, React Testing Library",
    "  • Performance profiling & optimization",
    "",
    "Leadership & Process:",
    "  • Technical Leadership",
    "  • Mentorship & Code Review",
    "  • Standards & Best Practices enforcement",
    "  • Cross-team coordination",
    "  • Architecture decision making",
  ],
  projects: [
    "🎯 Technical Challenges & Real Projects",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "These are examples of challenges I design for evaluating Frontend",
    "Engineers — and expect myself to be able to defend.",
    "",
    "1️⃣ Scalable Dashboard Architecture",
    "────────────────────────────────────────────────────────────────",
    "Design project structure, choose SSR/CSR strategy, separate domains,",
    "and prepare for team growth.",
    "",
    "  ✓ Implemented at Khodro45 with Monorepo (Nx)",
    "  ✓ Micro-Frontend ready for team independence",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "2️⃣ Real Design System",
    "────────────────────────────────────────────────────────────────",
    "Build components that are:",
    "",
    "  • SSR-safe",
    "  • Integrated with React Hook Form",
    "  • Clean and usable API",
    "",
    "  ✓ Custom Design System built from scratch at Khodro45",
    "  ✓ Enforced standards with automated validation",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "3️⃣ Smart State Management",
    "────────────────────────────────────────────────────────────────",
    "Precise separation of server state vs client state.",
    "Handle edge cases: refresh, back/forward, tab duplication.",
    "",
    "  ✓ Implemented complex state strategies at scale",
    "  ✓ React Query + Zustand architecture",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "4️⃣ Performance & Web Vitals",
    "────────────────────────────────────────────────────────────────",
    "Analyze bottlenecks. Real improvement of LCP, CLS, INP",
    "— not just Lighthouse numbers.",
    "",
    "  ✓ Achieved 100 Lighthouse scores at Keepa",
    "  ✓ Performance, Accessibility, Best Practices: all 100",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "5️⃣ Testing Strategy",
    "────────────────────────────────────────────────────────────────",
    "Conscious choice:",
    "",
    "  • What gets tested",
    "  • What doesn't get tested",
    "  • And why",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "6️⃣ Technical Leadership",
    "────────────────────────────────────────────────────────────────",
    "Managing technical disagreements.",
    "Enforcing standards without exhausting the team.",
    "",
    "  ✓ Led Frontend standards across multiple teams",
    "  ✓ Bridge between Frontend, Backend, Product, UX",
  ],
  experience: [
    "🏗️ Professional Experience",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "Staff Frontend Engineer – Khodro45",
    "────────────────────────────────────────────────────────────────",
    "One of Iran's largest automotive buying/selling platforms",
    "",
    "  • Redesigned Frontend architecture from ground up",
    "  • Complete migration to Monorepo (Nx) for team scalability",
    "  • Designed & implemented custom Design System with focus on",
    "    SSR and reusability",
    "  • Defined strict ESLint rules and file structure (preventing",
    "    wrong file creation)",
    "  • Currently working on Micro-Frontend Architecture for team",
    "    independence and separate deployments",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "Senior Frontend Engineer – Unipoly",
    "────────────────────────────────────────────────────────────────",
    "",
    "  • Created a dashboard featuring the latest data and metrics",
    "    for business stakeholders",
    "  • Defined and coordinated Frontend technical standards across",
    "    multiple teams",
    "  • Focused on performance, accessibility, and SEO",
    "  • Key project pages reached Lighthouse score of 100 in",
    "    Performance, Accessibility, and Best Practices",
    "  • Served as the bridge between Frontend, Backend, Product, and UX teams",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "Frontend Chapter Lead – Keepa",
    "────────────────────────────────────────────────────────────────",
    "",
    "  • Defined and coordinated Frontend technical standards across",
    "    multiple teams",
    "  • Heavy focus on performance, accessibility, and SEO",
    "  • Key project pages reached Lighthouse score of 100 in",
    "    Performance, Accessibility, and Best Practices",
    "  • Role wasn't just technical — I was the real bridge between",
    "    Frontend, Backend, Product, and UX teams",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "Senior / Mid Frontend Engineer – Pelazio",
    "────────────────────────────────────────────────────────────────",
    "",
    "  • Implemented real-scale React / Next.js applications",
    "  • Worked with various state management solutions",
    "    (Redux, React Query, Zustand)",
    "  • Product development, not just feature delivery",
    "  • Mentored junior developers and conducted thorough code reviews",
    "════════════════════════════════════════════════════════════════",
    "",
    "Junior Frontend Developer – Safarzoon",
    "────────────────────────────────────────────────────────────────",
    "",
    "  • Learned core Frontend fundamentals with React",
    "  • Delivered real product features, not just code",
  ],
  education: [
    "🎓 If You're Reading This...",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "If you're looking for someone who:",
    "",
    "  • Doesn't just deliver features",
    "  • But builds systems",
    "  • And delivers the team stronger than before",
    "",
    "We're probably talking about the right thing.",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "What I Can Do:",
    "",
    "  ✓ Turn this into a real Landing Page (HTML/React)",
    "  ✓ Short & Sharp version for Recruiters",
    "  ✓ Polished English version for international audience",
    "",
    "Tell me what you need — I'll make it happen.",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "My Philosophy:",
    "",
    '  "Quality is not a feature. It\'s a constraint."',
    "",
    "  I believe in:",
    "    • Writing code that the next person can read",
    "    • Architecture that survives team changes",
    "    • Standards that prevent problems, not fix them",
    "    • Systems that scale with minimal friction",
  ],
  contact: [
    "📧 Get in Touch",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "Professional Links:",
    "────────────────────────────────────────────────────────────────",
    "  • LinkedIn: linkedin.com/in/mohammad-garmabi",
    "  • GitHub: github.com/mohammad-garmabi",
    "  • NPM: npmjs.com/~mohammad.garmabi",
    "  • Email: Available on LinkedIn",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "I'm Open To:",
    "",
    "  ✓ Senior Frontend Engineering roles",
    "  ✓ Technical Leadership positions",
    "  ✓ Architecture & System Design consulting",
    "  ✓ Remote opportunities worldwide",
    "  ✓ Contract or Full-time",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "What I Bring:",
    "",
    "  • Real-world experience at scale (Khodro45, Keepa)",
    "  • Not just feature delivery — system building",
    "  • Technical leadership that strengthens teams",
    "  • Architecture decisions with long-term vision",
    "  • Standards that enforce quality, not recommend it",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "Response Time: Usually within 24-48 hours ⚡",
    "",
    "Let's build something that lasts. 🚀",
  ],
  packages: [
    "📦 NPM Packages:",
    "",
    "Loading package statistics from npm registry...",
    "",
    "Note: Use 'packages --refresh' to update stats",
  ],
  recommend: [
    "💌 Write a LinkedIn Recommendation",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "I'd greatly appreciate if you could write a recommendation for me",
    "on LinkedIn! It helps showcase my work and impact to others.",
    "",
    "👇 Click the button below to go to my LinkedIn profile:",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "📝 What You Could Include (if applicable):",
    "",
    "Technical Excellence:",
    "  • Architecture decisions and long-term thinking",
    "  • Code quality, maintainability, scalability",
    "  • React, TypeScript, Next.js, Modern Frontend",
    "  • Performance optimization, Web Vitals",
    "  • Design System development",
    "",
    "Leadership & Collaboration:",
    "  • Technical leadership and mentorship",
    "  • Cross-team coordination (Frontend, Backend, Product, UX)",
    "  • Standards enforcement without team exhaustion",
    "  • Problem-solving approach",
    "  • Knowledge sharing and documentation",
    "",
    "Impact:",
    "  • How I helped the team or project",
    "  • Specific achievements you witnessed",
    "  • Long-term improvements to systems",
    "  • Quality of deliverables",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "💡 Tips for a Great Recommendation:",
    "",
    "  1. Be specific about projects we worked on together",
    "  2. Mention particular skills or strengths you observed",
    "  3. Share a memorable achievement or contribution",
    "  4. Describe the lasting impact",
    "  5. Be authentic and genuine in your words",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "📌 How to Write on LinkedIn:",
    "",
    "  1. Click the button below (opens my profile in new tab)",
    "  2. Click 'More' button on my profile",
    "  3. Select 'Recommend'",
    "  4. Choose our relationship and position",
    "  5. Write your recommendation",
    "  6. Click 'Send'",
    "",
    "════════════════════════════════════════════════════════════════",
    "",
    "🙏 Thank you so much for taking the time!",
    "   Your support means a lot to me.",
    "",
    "PS: I'm happy to write one for you too! Just let me know. 🤝",
  ],
};

// Welcome Message
export const WELCOME_MESSAGE = [
  "╔═══════════════════════════════════════════════════════════════════╗",
  "║                  Mohammad Garmabi - Portfolio                     ║",
  "║                    Software Engineer                              ║",
  "╚═══════════════════════════════════════════════════════════════════╝",
  "",
  "👋 Welcome! Type 'help' to see available commands.",
  "",
  "💡 Quick Start:",
  "   • Type 'about' to learn who I am",
  "   • Type 'experience' to see my work history",
  "   • Type 'projects' to see technical challenges I solve",
  "",
  "⌨️  Navigation:",
  "   • Press Tab for command suggestions",
  "   • Use ↑↓ arrows to navigate history",
  "   • Right-click for quick menu",
  "",
];

// Theme Presets - Expanded Collection
export const THEME_PRESETS = [
  // Classic Terminals
  {
    name: "Classic Green",
    backgroundColor: "#0c0c0c",
    fontColor: "#00ff00",
    category: "classic",
  },
  {
    name: "Amber Terminal",
    backgroundColor: "#1a1a1a",
    fontColor: "#ffb000",
    category: "classic",
  },
  {
    name: "White on Black",
    backgroundColor: "#000000",
    fontColor: "#ffffff",
    category: "classic",
  },
  {
    name: "Green Phosphor",
    backgroundColor: "#001100",
    fontColor: "#33ff33",
    category: "classic",
  },
  
  // Modern Dark
  {
    name: "One Dark",
    backgroundColor: "#282c34",
    fontColor: "#abb2bf",
    category: "modern",
  },
  {
    name: "Dracula",
    backgroundColor: "#282a36",
    fontColor: "#f8f8f2",
    category: "modern",
  },
  {
    name: "Nord",
    backgroundColor: "#2e3440",
    fontColor: "#d8dee9",
    category: "modern",
  },
  {
    name: "Monokai",
    backgroundColor: "#272822",
    fontColor: "#f8f8f2",
    category: "modern",
  },
  {
    name: "Night Owl",
    backgroundColor: "#011627",
    fontColor: "#d6deeb",
    category: "modern",
  },
  {
    name: "Material Dark",
    backgroundColor: "#263238",
    fontColor: "#eeffff",
    category: "modern",
  },
  
  // Modern Light
  {
    name: "Light",
    backgroundColor: "#ffffff",
    fontColor: "#383a42",
    category: "light",
  },
  {
    name: "Solarized Light",
    backgroundColor: "#fdf6e3",
    fontColor: "#657b83",
    category: "light",
  },
  {
    name: "GitHub Light",
    backgroundColor: "#ffffff",
    fontColor: "#24292e",
    category: "light",
  },
  {
    name: "Atom Light",
    backgroundColor: "#fafafa",
    fontColor: "#383a42",
    category: "light",
  },
  
  // Colorful
  {
    name: "Cobalt2",
    backgroundColor: "#193549",
    fontColor: "#ffffff",
    category: "colorful",
  },
  {
    name: "Synthwave",
    backgroundColor: "#2b213a",
    fontColor: "#ff7edb",
    category: "colorful",
  },
  {
    name: "Ocean",
    backgroundColor: "#1b2b34",
    fontColor: "#c0c5ce",
    category: "colorful",
  },
  {
    name: "Cyberpunk",
    backgroundColor: "#000b1e",
    fontColor: "#00ffff",
    category: "colorful",
  },
  {
    name: "Neon",
    backgroundColor: "#0a0e27",
    fontColor: "#00ff41",
    category: "colorful",
  },
  {
    name: "Sunset",
    backgroundColor: "#1a1a2e",
    fontColor: "#ff6b6b",
    category: "colorful",
  },
  
  // Special
  {
    name: "Matrix",
    backgroundColor: "#000000",
    fontColor: "#00ff00",
    category: "special",
  },
  {
    name: "Hacker",
    backgroundColor: "#0d0208",
    fontColor: "#00ff41",
    category: "special",
  },
  {
    name: "Retro",
    backgroundColor: "#2c1810",
    fontColor: "#ffaa00",
    category: "special",
  },
  {
    name: "Minimal Gray",
    backgroundColor: "#1e1e1e",
    fontColor: "#cccccc",
    category: "special",
  },
] as const;

// Default Settings
export const DEFAULT_SETTINGS = {
  fontSize: 14,
  backgroundColor: "#0c0c0c",
  fontColor: "#00ff00",
};

// Local Storage Key
export const SETTINGS_STORAGE_KEY = "terminal-settings";

